create extension if not exists pgcrypto;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,name text,avatar_url text,phone text,username text unique,created_at timestamptz default now());
create table if not exists public.public_chat_messages(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,message text not null check(length(message)<=2000),created_at timestamptz default now());
create table if not exists public.project_requests(id uuid primary key default gen_random_uuid(),user_id uuid references auth.users(id) on delete cascade,title text not null,details text,status text not null default 'pending' check(status in ('pending','approved','rejected')),created_at timestamptz default now());
create table if not exists public.direct_messages(id uuid primary key default gen_random_uuid(),sender_id uuid references auth.users(id) on delete cascade,receiver_id uuid references auth.users(id) on delete cascade,message text not null check(length(message)<=2000),created_at timestamptz default now());
alter table public.profiles enable row level security; alter table public.public_chat_messages enable row level security; alter table public.project_requests enable row level security; alter table public.direct_messages enable row level security;
create policy "profiles read" on public.profiles for select using (true);
create policy "own profile update" on public.profiles for update using (auth.uid()=id);
create policy "own profile insert" on public.profiles for insert with check (auth.uid()=id);
create policy "chat read" on public.public_chat_messages for select using (true);
create policy "chat insert own" on public.public_chat_messages for insert with check (auth.uid()=user_id);
create policy "requests own read" on public.project_requests for select using (auth.uid()=user_id);
create policy "requests own insert" on public.project_requests for insert with check (auth.uid()=user_id);
create policy "dm participants read" on public.direct_messages for select using (auth.uid()=sender_id or auth.uid()=receiver_id);
create policy "dm sender insert" on public.direct_messages for insert with check (auth.uid()=sender_id);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,name) values(new.id,new.raw_user_meta_data->>'name'); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
