import {useEffect,useState} from "react";
import {getPublicPlaybackConfig} from "../lib/adminApi";
import Hls from "hls.js";
type Props={tmdbId:number;type:"movie"|"tv";season?:number;episode?:number;poster?:string;title?:string};
function expandTemplate(template:string,tmdbId:number,type:"movie"|"tv",season:number,episode:number){return template.replaceAll("{tmdbId}",String(tmdbId)).replaceAll("{type}",type).replaceAll("{season}",String(season)).replaceAll("{episode}",String(episode));}
export default function VideoPlayer({tmdbId,type,season=1,episode=1,poster,title}:Props){
const [sources,setSources]=useState<string[]>([]); const [selected,setSelected]=useState(0); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [speed,setSpeed]=useState(1); const [playerError,setPlayerError]=useState("");
useEffect(()=>{let alive=true;setLoading(true);setError("");setSelected(0);getPublicPlaybackConfig().then(cfg=>{if(!alive)return;const custom=(cfg.custom_streams||[]).filter((x:any)=>String(x.tmdbId)===String(tmdbId)&&x.type===type&&x.url).map((x:any)=>String(x.url));const configured=(cfg.server_urls||[]).filter(Boolean).map((x:string)=>expandTemplate(x,tmdbId,type,season,episode));const all=[...custom,...configured].filter((x,i,a)=>x&&!a.slice(0,i).includes(x));setSources(all);if(!all.length)setError("لا يوجد مصدر مشاهدة مهيأ لهذا المحتوى حالياً.");}).catch(()=>{if(alive)setError("تعذر تحميل مصادر المشاهدة.");}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false};},[tmdbId,type,season,episode]);
const src=sources[selected]||"";
useEffect(()=>{setPlayerError("");const v=document.querySelector<HTMLVideoElement>("[data-final-player]");if(!v||!src)return;v.playbackRate=speed;let h:Hls|undefined;const onError=()=>setPlayerError("تعذر تشغيل هذا المصدر. جرّب المصدر التالي.");v.addEventListener("error",onError);if(/\.m3u8(?:$|[?#])/i.test(src)&&Hls.isSupported()){h=new Hls({enableWorker:true});h.on(Hls.Events.ERROR,(_:any,d:any)=>{if(d.fatal)setPlayerError("تعذر تشغيل هذا المصدر. جرّب المصدر التالي.");});h.loadSource(src);h.attachMedia(v);}else if(v.canPlayType("application/vnd.apple.mpegurl"))v.src=src;else v.src=src;return()=>{v.removeEventListener("error",onError);h?.destroy();v.pause();};},[src,speed]);
return <div className="player"><div className="player-video-wrap">{loading?<div className="loading">جاري تجهيز المشغل…</div>:src?<video key={src} data-final-player poster={poster} controls playsInline preload="metadata"/>:<div className="loading">{error}</div>}</div>{title&&<div className="player-title">{title}</div>}<div className="player-tools"><span>{sources.length?"المصادر المتاحة: "+sources.length:"لا يوجد مصدر"}</span><label>السرعة <select value={speed} onChange={e=>setSpeed(Number(e.target.value))}>{[.5,.75,1,1.25,1.5,2].map(x=><option key={x} value={x}>{x}x</option>)}</select></label>{sources.length>1&&<select value={selected} onChange={e=>setSelected(Number(e.target.value))}>{sources.map((_,i)=><option key={i} value={i}>مصدر {i+1}</option>)}</select>}</div>{playerError&&<p className="error">{playerError}</p>}</div>;
}